version: '2'
services:
  db:
    image: mongo
    command: "--smallfiles --logpath=/dev/null"
  redis:
    image: redis
  greenbot-core:
    image: greenbot/greenbot-core
    depends_on:
      - db
      - redis
    command: npm start
    ports:
      - "3001:3001"
      - "3003:3003"
    links:
      - db
      - redis
    environment:
      PORT: 3001 # this is optional, allows express to use process.env.PORT instead of a raw
      REDIS_PORT: 6379
      REDIS_HOST: redis
      MONGO_URL: mongodb://db:27017/greenbot
      TRACE_MESSAGES: why_not
  greenbot-admin:
    image: greenbot/greenbot-admin
    depends_on:
      - db
    ports:
      - "8080:80"
    links:
      - db
      - greenbot-core
    volumes: 
       - /root/code/bundle:/bundle
    environment:
      MONGO_URL: mongodb://db:27017/greenbot
      ROOT_URL: ${ROOT_URL}
      GREENBOT_IO_URL: ${ROOT_URL}:3003
