source 'https://rubygems.org'

gem 'airbrake' 
gem 'awesome_print' 
gem 'bigdecimal' 
gem 'builder' 
gem 'bundler' 
gem 'bundler-unload' 
gem 'coderay' 
gem 'eventmachine' 
gem 'executable-hooks' 
gem 'gem-wrappers' 
gem 'gmail' 
gem 'gmail_xoauth' 
gem 'highline', ">=1.7.1"
gem 'io-console', "0.4.2"
gem 'json' 
gem 'mail' 
gem 'method_source' 
gem 'mime-types' 
gem 'minitest' 
gem 'multi_json' 
gem 'nexmo' 
gem 'oauth' 
gem 'power_assert' 
gem 'pry' 
gem 'psych' 
gem 'rake' 
gem 'rdoc' 
gem 'redis' 
gem 'redis-semaphore' 
gem 'rubygems-bundler' 
gem 'rvm' 
gem 'slop' 
gem 'test-unit' 
gem 'uuidtools' 
